# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      publish_artifacts:
        description: 'Publish artifacts'
        required: false
        default: 'true'
      Env:
        description: "Select environment"
        required: true
        default: 'Test'   
    
jobs:  
  Deploy_To_Dev:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build && ls -lrt ./build/libs/
    - if: github.event.inputs.publish_artifacts == 'true' && github.event.inputs.Env == 'Dev'
      name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: pandeyaws/alok
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
        
        
         
